name: iot-platform-frontend-deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      # Clean old dist folder on server first
      - name: Clean old dist folder
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            rm -rf ${{ secrets.VPS_PATH }}/dist
            mkdir -p ${{ secrets.VPS_PATH }}/dist

      # Upload dist folder to server
      - name: Upload dist to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/*"
          target: "${{ secrets.VPS_PATH }}"
          strip_components: 0

      # Restart PM2
      - name: Restart PM2 on server
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ${{ secrets.VPS_PATH }}
            pm2 delete react-frontend || true
            pm2 serve dist 3000 --name "react-frontend" --spa
            pm2 save
