import { EdgeInstance, EdgeActivity } from './types';

// ... (existing edgeInstances code)

export const edgeActivities: EdgeActivity[] = [
  {
    id: 'act-1',
    instanceId: '1',
    instanceName: 'Factory Floor - Building A',
    type: 'success',
    action: 'Data Sync Completed',
    timestamp: new Date(Date.now() - 1000 * 60 * 5),
    details: 'Synchronized 156 telemetry records successfully.',
  },
  {
    id: 'act-2',
    instanceId: '3',
    instanceName: 'Remote Site - Mining',
    type: 'warning',
    action: 'High CPU Usage',
    timestamp: new Date(Date.now() - 1000 * 60 * 15),
    details: 'CPU usage exceeded 85% for more than 10 minutes.',
  },
  {
    id: 'act-3',
    instanceId: '4',
    instanceName: 'Branch Office - Seattle',
    type: 'error',
    action: 'Instance Offline',
    timestamp: new Date(Date.now() - 1000 * 60 * 60),
    details: 'Connection lost. Heartbeat failed.',
  },
  {
    id: 'act-4',
    instanceId: '2',
    instanceName: 'Warehouse - Distribution Center',
    type: 'info',
    action: 'Version Update',
    timestamp: new Date(Date.now() - 1000 * 60 * 120),
    details: 'System updated to version 3.5.2.',
  },
];

export const edgeInstances: EdgeInstance[] = [
  {
    id: '1',
    name: 'Factory Floor - Building A',
    location: 'New York, USA',
    status: 'online',
    version: '3.5.2',
    ipAddress: '192.168.1.100',
    lastSeen: new Date(),
    devices: 45,
    cpu: 42,
    memory: 68,
    storage: 55,
    uptime: '15d 4h 23m',
    dataSync: {
      pending: 0,
      lastSync: new Date('2025-01-30T14:30:00'),
    },
  },
  {
    id: '2',
    name: 'Warehouse - Distribution Center',
    location: 'Los Angeles, USA',
    status: 'online',
    version: '3.5.2',
    ipAddress: '192.168.2.100',
    lastSeen: new Date(),
    devices: 67,
    cpu: 38,
    memory: 55,
    storage: 72,
    uptime: '22d 11h 45m',
    dataSync: {
      pending: 0,
      lastSync: new Date('2025-01-30T14:28:00'),
    },
  },
  {
    id: '3',
    name: 'Remote Site - Mining',
    location: 'Denver, USA',
    status: 'syncing',
    version: '3.5.1',
    ipAddress: '10.0.1.50',
    lastSeen: new Date(Date.now() - 120000),
    devices: 23,
    cpu: 65,
    memory: 72,
    storage: 45,
    uptime: '7d 18h 12m',
    dataSync: {
      pending: 156,
      lastSync: new Date('2025-01-30T14:00:00'),
    },
  },
  {
    id: '4',
    name: 'Branch Office - Seattle',
    location: 'Seattle, USA',
    status: 'offline',
    version: '3.5.0',
    ipAddress: '10.0.2.75',
    lastSeen: new Date(Date.now() - 3600000),
    devices: 12,
    cpu: 0,
    memory: 0,
    storage: 0,
    uptime: '-',
    dataSync: {
      pending: 1234,
      lastSync: new Date('2025-01-30T10:00:00'),
    },
  },
];
